blogapp/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
-------------------------------------------------------------
    Creator : 汪春旺
       Date : 2019-05-25
    Project : myblog
   FileName : urls.py
Description : 
-------------------------------------------------------------
"""
from django.urls import path
from blogapp.views import *

app_name = 'blogapp'

urlpatterns = [
    # 首页
    path('', IndexView.as_view(), name='index'),

    # 文章分类菜单，显示该分类下所有文章列表。需注意url冲突。
    path('<str:catecode>-list', ArticalListView.as_view(), name='article_list'),
    # 文章详情
    path('<str:catecode>/<int:pk>', ArticalDetailView.as_view(), name='article_detail'),
    # 标签
    path('tag/<str:tagcode>-list', TagView.as_view(), name='tag_article_list'),
    # 搜索关键字
    path('search', SearchView.as_view(), name='search'),
    # 关于博主
    path('about', AboutView.as_view(), name='about'),

]

extraapps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views import static

from myblog import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('ueditor', include('extraapps.DjangoUeditor.urls')),      # 添加DjangoUeditor的URL
    re_path('^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),     # Ueditor富文本上传图片，不支持path新方法！

    # blogapp URL
    path('', include('blogapp.urls')),
]

blogapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils.html import format_html

from extraapps.DjangoUeditor.models import UEditorField


class Category(models.Model):
    """
    文章分类字典表
    """
    code = models.CharField(verbose_name='分类编码', max_length=4, unique=True)
    name = models.CharField(verbose_name='分类名称', max_length=20)
    index = models.IntegerField(verbose_name='排序', default=999)

    class Meta:
        verbose_name = '文章分类字典表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签字典表
    """
    code = models.CharField(verbose_name='标签编码', max_length=4, unique=True)
    name = models.CharField(verbose_name='标签名称', max_length=20)

    class Meta:
        verbose_name = '标签字典表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Recom(models.Model):
    """
    推荐位字典表
    """
    code = models.CharField(verbose_name='推荐位编码', max_length=4, unique=True)
    name = models.CharField(verbose_name='推荐位', max_length=20)

    class Meta:
        verbose_name = '推荐位字典表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Artical(models.Model):
    """
    博客文章表
    """
    title = models.CharField(verbose_name='标题', max_length=100)
    category = models.ForeignKey(verbose_name='分类id', to=Category, on_delete=models.DO_NOTHING, blank=True, null=True)
    tags = models.ManyToManyField(verbose_name='标签id', to=Tag, blank=True)
    img = models.ImageField(verbose_name='文章图片', upload_to='artical-img/%Y-%m', blank=True, null=True)
    excerpt = models.CharField(verbose_name='摘要', max_length=100, blank=True, null=True)
    # Ueditor是百度开发的一个富文本编辑器，功能强大。用富文本编辑body
    body = UEditorField(verbose_name='内容', width=800, height=500, imagePath='up-img/', filePath='up-file/',
                        upload_settings={'imageMaxSize': 1204000}, blank=True, null=True)
    user = models.ForeignKey(verbose_name='作者id', to=User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(verbose_name='浏览量', default=0)
    recom = models.ForeignKey(verbose_name='推荐位id', to=Recom, on_delete=models.DO_NOTHING, blank=True, null=True)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    modi_time = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        verbose_name = '博客文章表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Banner(models.Model):
    """
    轮播图片表
    """
    text_info = models.CharField(verbose_name='标题', max_length=50, default='')
    img = models.ImageField(verbose_name='轮播图片', upload_to='banner/')
    link_url = models.URLField(verbose_name='图片链接', max_length=100)
    is_active = models.BooleanField(verbose_name='是否可用', default=False)

    def link_url_color(self):
        """
        根据状态，给字段添加CSS颜色显示
        :return:
        """
        if self.is_active is True:
            f_color = 'green'
        else:
            f_color = 'gray'
        return format_html('<span style="color: {}">{}</span>', f_color, self.link_url)

    class Meta:
        verbose_name = '轮播图表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.text_info


class Link(models.Model):
    """
    友情链接表
    """
    name = models.CharField(verbose_name='链接名称', max_length=20)
    link_url = models.URLField(verbose_name='网址', max_length=100)

    class Meta:
        verbose_name = '友情链接表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

blogapp/views.py
from django.core import paginator
from django.db.models import Q
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import View
from blogapp.models import *


def get_globalvars(request):
    # 查询文章分类导航
    cates = Category.objects.all()[:5]
    # 热门推荐，根据推荐字典取R02
    reco2_articals = Artical.objects.filter(recom__code='R02').order_by('-create_time')[:4]
    # 所有标签
    tags = Tag.objects.all()
    return locals()


class IndexView(View):
    """
    首页视图
    """

    def get(self, request):
        # # 查询文章分类导航
        # cates = Category.objects.all()[:5]
        # # 热门推荐，根据推荐字典取R02
        # reco2_articals = Artical.objects.filter(recom__code='R02').order_by('-create_time')[:4]
        # # 所有标签
        # tags = Tag.objects.all()

        # 轮播图
        banners = Banner.objects.filter(is_active=True)[:4]

        # 首页推荐阅读
        reco_articals = Artical.objects.filter(recom__code='R01').order_by('-create_time')[:3]
        # 最新文章
        latest_articals = Artical.objects.order_by('-create_time')[:5]
        # 热门文章，按浏览量
        hot_articals = Artical.objects.order_by('-views')[:5]

        # 友情链接
        links = Link.objects.all()

        context = {
            # 'cates': cates,
            'banners': banners,
            'reco_articals': reco_articals,
            'latest_articals': latest_articals,
            'hot_articals': hot_articals,
            # 'reco2_articals': reco2_articals,
            # 'tags': tags,
            'links': links,
        }
        context.update(get_globalvars(request))
        return render(request=request, template_name='blogapp/index.html', context=context)


class ArticalListView(View):
    """
    不同分类的文章列表
    """

    def get(self, request, catecode):
        # # 查询文章分类导航
        # cates = Category.objects.all()[:5]
        # # 热门推荐，根据推荐字典取R02
        # reco2_articals = Artical.objects.filter(recom__code='R02').order_by('-create_time')[:4]
        # # 所有标签
        # tags = Tag.objects.all()

        # 获取文章列表
        articals = Artical.objects.filter(category__code=catecode).order_by('-create_time')
        # 获取分类
        cate = Category.objects.get(code=catecode)

        # 分页
        pn = paginator.Paginator(articals, per_page=2)  # 实例化分页器对象
        page_num = request.GET.get('page')  # 获取当前页码
        try:
            page_list_obj = pn.page(page_num)  # 进行分页，返回数据列表（将之传给模板）
        except paginator.PageNotAnInteger:
            page_list_obj = pn.page(1)
        except paginator.InvalidPage:
            page_list_obj = pn.page(pn.num_pages)

        context = {
            'cate': cate,
            'page_list_obj': page_list_obj,
            # 'reco2_articals': reco2_articals,
            # 'tags': tags,
            # 'cates': cates,
            'catecode': catecode,
        }
        context.update(get_globalvars(request))

        return render(request=request, template_name='blogapp/list.html', context=context)


class ArticalDetailView(View):
    """
    文章详情页
    """

    def get(self, request, catecode, pk):
        # # 查询文章分类导航
        # cates = Category.objects.all()[:5]
        # # 热门推荐，根据推荐字典取R02
        # reco2_articals = Artical.objects.filter(recom__code='R02').order_by('-create_time')[:4]
        # # 所有标签
        # tags = Tag.objects.all()

        # 可能感兴趣文章
        interest_articals = Artical.objects.filter(category__code=catecode).exclude(pk=pk).order_by('?')[:5]
        # 要显示详情的文章
        this_artical = Artical.objects.get(pk=pk)
        # 上一篇
        pre_artical = Artical.objects.filter(create_time__gt=this_artical.create_time, category__code=catecode).first()
        # 下一篇
        next_artical = Artical.objects.filter(create_time__lt=this_artical.create_time, category__code=catecode).last()
        # 浏览量+1
        this_artical.views += 1
        this_artical.save()
        context = locals()
        context.update(get_globalvars(request))
        return render(request=request, template_name='blogapp/show.html', context=context)


class TagView(View):
    """
    按标签显示文章列表
    """

    def get(self, request, tagcode):
        # # 查询文章分类导航
        # cates = Category.objects.all()[:5]
        # # 热门推荐，根据推荐字典取R02
        # reco2_articals = Artical.objects.filter(recom__code='R02').order_by('-create_time')[:4]
        # # 所有标签
        # tags = Tag.objects.all()

        # 根据标签查询文章列表
        tag_articals = Artical.objects.filter(tags__code=tagcode).order_by('-create_time')
        # 获取标签名
        tag_name = Tag.objects.get(code=tagcode)

        # 分页
        pn = paginator.Paginator(tag_articals, 2)  # 实例化分页器对象
        page_num = request.GET.get('page')  # 获取当前页码
        try:
            page_list_obj = pn.page(page_num)  # 进行分页，返回数据列表（将之传给模板）
        except paginator.PageNotAnInteger:
            page_list_obj = pn.page(1)
        except paginator.InvalidPage:
            page_list_obj = pn.page(pn.num_pages)
        context = locals()
        context.update(get_globalvars(request))
        return render(request=request, template_name='blogapp/tags.html', context=context)


class SearchView(View):
    """
    按标题或内容关键字搜索文章
    """

    def get(self, request):
        # # 查询文章分类导航
        # cates = Category.objects.all()[:5]
        # # 热门推荐，根据推荐字典取R02
        # reco2_articals = Artical.objects.filter(recom__code='R02').order_by('-create_time')[:4]
        # # 所有标签
        # tags = Tag.objects.all()

        # 获取关键字
        keyword = request.GET.get('keyword', '')
        if keyword:
            search_articles = Artical.objects.filter(Q(title__icontains=keyword) | Q(body__icontains=keyword))
        else:
            search_articles = Artical.objects.order_by('-create_time')

        # 分页
        pn = paginator.Paginator(search_articles, 4)  # 实例化分页器对象
        page_num = request.GET.get('page')  # 获取当前页码
        try:
            page_list_obj = pn.page(page_num)  # 分页，返回数据列表
        except paginator.PageNotAnInteger:
            page_list_obj = pn.page(1)
        except paginator.InvalidPage:
            page_list_obj = pn.page(pn.num_pages)
        context = locals()
        context.update(get_globalvars(request))
        return render(request, template_name='blogapp/search.html', context=context)


class AboutView(View):
    """
    关于页
    """

    def get(self, request):
        # 查询文章分类导航
        cates = Category.objects.all()[:5]

        return render(request, template_name='blogapp/about.html', context={'cates': cates})

blogapp/templates/blogapp/base.html
{% load staticfiles %}
<!--用于继承-->
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-dns-prefetch-control" content="on"/>
    <meta http-equiv="X-UA-Compatible" content="IE=11,IE=10,IE=9,IE=8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-title" content="汪春旺个人博客网站">
    <title>汪春旺个人博客网站</title>
    <link href="{% static 'blogapp/images/title.ico' %}" rel="icon" type="image/x-ico">
    <link rel='stylesheet' id='bootstrap-css' href='{% static "blogapp/css/bootstrap.min.css" %}' type='text/css'
          media='all'/>
    <link rel='stylesheet' id='fontawesome-css' href='{% static "blogapp/css/font-awesome.min.css" %}' type='text/css'
          media='all'/>
    <link rel='stylesheet' id='stylesheet-css' href='{% static "blogapp/css/style.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' id='raxus-css' href='{% static "blogapp/css/raxus.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' id='open-social-style-css' href='{% static "blogapp/css/os.css" %}' type='text/css'
          media='all'/>
    <meta name='robots' content='index,follow'/>
    <meta name="keywords" content="互联网,产品经理,产品设计,用户体验,交互设计,网站运营,移动互联网">
    <meta name="description" content="聚焦互联网前沿资讯，网络精华内容，交流产品心得。 每天为你速递最新、最鲜、最有料的互联网科技资讯！">
</head>
<body class="home blog site-layout-2">
<!-- 头部 -->
<header class="fix-wrap" id="fix-wrap">
    <div class="fix-main clearfix pr" id="fix-main" _hover-ignore="1">
        <a href="{% url 'blogapp:index' %}" class="index-logo"><img src="{% static "blogapp/picture/black-logo.png" %}"
                                                                    alt="汪春旺个人博客网站"/></a>
        <nav class="nav fl">
            <ul id="fix-list" class="fix-list clearfix">
                <li id="menu-item-24086" class="menu-item"><a href="{% url 'blogapp:index' %}">首页</a></li>
                {% for cate in cates %}
                    <li id="menu-item-117720" class="menu-item">
                        <a href="{% url 'blogapp:article_list' cate.code %}">{{ cate.name }}</a></li>
                {% endfor %}
                <li id="menu-item-24086" class="menu-item"><a href="{% url 'blogapp:about' %}">关于</a></li>
            </ul>
        </nav>
        <!--搜索栏 通过GET发送请求-->
        <form method="get" class="index-search  hidden-xs" action="{% url 'blogapp:search' %}">
            <input class="text" name="keyword" type="text" placeholder="输入关键字" value="{{ keyword }}">
            <button class="submit" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
</header>

{% block content %}
{% endblock %}

<!-- 底部 -->
<footer class="footer">
    <div class="copyright"> © 2019- 2020 · All Rights Reserved
        · <a href="http://www.cnblogs.com/wcwnina/">汪春旺中文网</a>
        · <a href="http://www.miibeian.gov.cn" target="_blank">粤ICP备17023990号</a> 版权所有 © 汪春旺中文网
    </div>
</footer>
{#<script src="{% static "blogapp/js/bundle.js" %}"></script>#}
<script type="text/javascript" src="{% static "blogapp/js/view-history.js" %}"></script>
<script type='text/javascript' src="{% static "blogapp/js/push.js" %}"></script>
<script type='text/javascript' src='{% static "blogapp/js/jquery.min.js" %}'></script>
<script type='text/javascript' src='{% static "blogapp/js/bootstrap.min.js" %}'></script>
<script type='text/javascript' src='{% static "blogapp/js/raxus-slider.min.js" %}'></script>
<script type='text/javascript' src='{% static "blogapp/js/loader.js" %}'></script>
<script type='text/javascript' src='{% static "blogapp/js/bj-lazy-load.min.js" %}'></script>
<script type='text/javascript' src='{% static "blogapp/js/os.js" %}'></script>

</body>
</html>

blogapp/templates/blogapp/list.html
{% extends "blogapp/base.html" %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blogapp:index' %}">首页</a> » <span
                    class="current">{{ cate.name }} </span>
            </div>
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title">分类：{{ cate.name }}</h4>
                </div>
                <div class="row">

                    {% for artical in page_list_obj %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'blogapp:article_detail' catecode artical.pk %}"
                                       title="{{ artical.title }}">
                                        <img src="{{ MEDIA_URL }}{{ artical.img }}"
                                             srcset="{{ MEDIA_URL }}{{ artical.img }}"
                                             alt="{{ artical.title }}" class="wp-post-image" width="240" height="160"/></a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'blogapp:article_detail' catecode artical.pk %}" target="_blank"
                                       title="{{ artical.title }}">{{ artical.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a
                                        href="{% url 'blogapp:article_detail' catecode artical.pk %}"
                                        target="_blank"
                                        title="{{ artical.title }}">{{ artical.excerpt }}</a>
                                </p>
                                <div class="meta"><span class="label label-info"><a
                                        href="{% url 'blogapp:article_list' catecode %}">{{ artical.category.name }}</a></span>
                                    <time class="item"><i
                                            class="fa fa-clock-o"></i>{{ artical.create_time|date:"Y年m月d日 H:i:s" }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <!--分页机制-->
                    <div class="pagination">
                        <ul>
                            {% if page_list_obj.has_previous %}
                                <li class="prev-page"><a href="?page={{ page_list_obj.previous_page_number }}">上一页</a></li>
                            {% else %}
                                <li class="prev-page"></li>
                            {% endif %}


                            {% for num in page_list_obj.paginator.page_range %}
                                {% if num %}
                                    {% ifequal num page_list_obj.number %}
                                        <li class="active"><span>{{ num }}</span></li>
                                    {% else %}
                                        <li><a href="?page={{ num }}">{{ num }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="disabled"><span>...</span></li>
                                {% endif %}
                            {% endfor %}


                            {% if page_list_obj.has_next %}
                                <li class="next-page"><a href="?page={{ page_list_obj.next_page_number }}">下一页</a></li>
                            {% else %}
                                <li class="prev-page"></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <!-- /右侧列表 -->

        <!-- /post-left -->
        <!-- /post-right -->
        <aside class="post-right hidden-xs">

            {% include 'blogapp/right.html' %}

        </aside>

    </div>
{% endblock %}

blogapp/templates/blogapp/right.html
{% load staticfiles %}
<section class="widget post-right-item">
    <h4 class="post-right-title">热门推荐</h4>
    <ul class="post-hot clearfix">
        {% for reco2_artical in reco2_articals %}
            <li>
                <div class="img">
                    <a href="{% url 'blogapp:article_detail' reco2_artical.category.code reco2_artical.pk %}" title="{{ reco2_artical.title }}">
                        <img src="{{ MEDIA_URL }}{{ reco2_artical.img }}" srcset="{{ MEDIA_URL }}{{ reco2_artical.img }}" alt="{{ reco2_artical.title }}"
                             class="wp-post-image" width="120" height="80"/>
                    </a>
                </div>
                <div class="text">
                    <a href="{% url 'blogapp:article_detail' reco2_artical.category.code reco2_artical.pk %}" title="{{ reco2_artical.title }}"
                       target="_blank">{{ reco2_artical.title }}</a>
                </div>
            </li>
        {% endfor %}
    </ul>
</section>

<section class="widget post-right-item"><h4 class="post-right-title">所有标签</h4>
    <div class="tags">
        {% for tag in tags %}
            <a href="{% url 'blogapp:tag_article_list' tag.code %}">{{ tag.name }}</a>
        {% endfor %}
    </div>
</section>
<!-- /关注我们 -->
<div class="post-right-item">
    <h4 class="post-right-title">关注我</h4>
    <div class="wid-about">
        <p>汪春旺博客网站，欢迎关注！</p>
        <img src="{% static "blogapp/picture/微信支付.jpg" %}" alt="微信二维码" width="160" height="220">
    </div>
    <div class="wid-about">
        <p><strong>联系方式:</strong></p>
        <p>QQ:2284914944</p>
        <p>Email：2284914944@qq.com</p>
    </div>
</div>

blogapp/templates/blogapp/search.html
{% extends 'blogapp/base.html' %}
{% block content %}
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blogapp:index' %}">首页</a> »
                <span class="current">关键词：{{ keyword }}</span></div>
            <div class="index-main clearfix">
                <div class="main-title">
                    <h4 class="post-left-title">关键词：{{ keyword }}</h4>
                </div>
                <div class="row">

                    {% for article in page_list_obj %}
                        <div class="article-box clearfix excerpt-1">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'blogapp:article_detail' article.category.code article.pk %}"
                                       title="{{ article.title }}">
                                        <img src="{{ MEDIA_URL }}{{ article.img }}"
                                             srcset="{{ MEDIA_URL }}{{ article.img }}"
                                             alt="{{ article.title }}" class="wp-post-image" width="240" height="160"/></a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h2><a href="{% url 'blogapp:article_detail' article.category.code article.pk %}"
                                       target="_blank"
                                       title="{{ article.title }}">{{ article.title }}</a></h2>
                                <p class="txtcont hidden-xs"><a
                                        href="{% url 'blogapp:article_detail' article.category.code article.pk %}"
                                        target="_blank"
                                        title="{{ article.title }}">{{ article.excerpt }}</a></p>
                                <div class="meta"><span class="label label-info"><a
                                        href="{% url 'blogapp:article_detail' article.category.code article.pk %}">{{ article.category.name }}</a></span>
                                    <time class="item"><i
                                            class="fa fa-clock-o"></i>{{ article.create_time|date:"Y年m月d日 H:i:s" }}
                                    </time>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <!--分页机制-->
                    <div class="pagination">
                        <ul>
                            {% if page_list_obj.has_previous %}
                                <li class="prev-page"><a
                                        href="{% url 'blogapp:search' %}?keyword={{ keyword }}&page={{ page_list_obj.previous_page_number }}">上一页</a>
                                </li>
                            {% else %}
                                <li class="prev-page"></li>
                            {% endif %}


                            {% for num in page_list_obj.paginator.page_range %}
                                {% if num %}
                                    {% ifequal num page_list_obj.number %}
                                        <li class="active"><span>{{ num }}</span></li>
                                    {% else %}
                                        <li>
                                            <a href="{% url 'blogapp:search' %}?keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                                        </li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="disabled"><span>...</span></li>
                                {% endif %}
                            {% endfor %}


                            {% if page_list_obj.has_next %}
                                <li class="next-page"><a
                                        href="{% url 'blogapp:search' %}?keyword={{ keyword }}&page={{ page_list_obj.next_page_number }}">下一页</a>
                                </li>
                            {% else %}
                                <li class="prev-page"></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        <aside class="post-right hidden-xs">

            {% include 'blogapp/right.html' %}

        </aside>
    </div>
{% endblock %}

blogapp/templates/blogapp/show.html
{% extends "blogapp/base.html" %}
{% block content %}
    <!-- /主体 -->
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="{% url 'blogapp:index' %}">首页</a> » <a
                    href="{% url 'blogapp:article_list' catecode %}">{{ this_artical.category.name }}</a> »
                <span class="current">正文</span></div>
            <div class="post-main clearfix">
                <h1 class="post-title">{{ this_artical.title }}</h1>
                <div class="post-con clearfix">
                    <div class="article-meta">
                        <span class="item">分类：<a href="{% url 'blogapp:article_list' catecode %}"
                                                 rel="category tag">{{ this_artical.category.name }}</a></span>
                        <span class="item">作者：{{ this_artical.user }}</span>
                        <span class="item">浏览：{{ this_artical.views }}</span>
                        <span class="item">{{ this_artical.create_time|date:'Y年m月d日 H:i:s' }}</span>

                    </div>
                    <article class="article-content">
                        {{ this_artical.body|safe }}
                    </article>

                    <div class="post-tag"><span class="fa fa-tags" aria-hidden="true"></span>标签：
                        {% for tag in this_artical.tags.all %}
                            <a href="{% url 'blogapp:tag_article_list' tag.code %}" rel="tag">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                    <div>
                        <div><b>上一篇：</b>
                            {% if next_artical %}
                                <a href="{% url 'blogapp:article_detail' catecode next_artical.pk %}" class="article-tag">{{ next_artical }}</a>
                            {% else %}
                                没有了
                            {% endif %}
                        </div>
                        <div><b>下一篇：</b>
                            {% if pre_artical %}
                                <a href="{% url 'blogapp:article_detail' catecode pre_artical.pk %}" class="article-tag">{{ pre_artical }}</a>
                            {% else %}
                                没有了
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
            <!-- /文章 -->


            <div class="recommend  hidden-xs">

                <div class="head clearfix"><span class="sp">您可能感兴趣的:</span></div>
                <ul>
                    {% for inte in interest_articals %}
                        <li>
                            <div class="pic">
                                <a href="{% url 'blogapp:article_detail' catecode inte.pk %}" title="{{ inte.title }}"><img
                                        src="{{ MEDIA_URL }}{{ inte.img }}"
                                        srcset="{{ MEDIA_URL }}{{ inte.img }}"
                                        alt="{{ inte.title }}" class="wp-post-image" width="145"
                                        height="100"/></a>
                            </div>
                            <a class="descript " href="{% url 'blogapp:article_detail' catecode inte.pk %}" rel="bookmark"
                               title="{{ inte.title }}">{{ inte.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>


        </section>
        <!-- /post-left -->
        <!-- /post-right -->
        <aside class="post-right hidden-xs">

            {% include 'blogapp/right.html' %}

        </aside>

    </div>
    <!-- /主体 -->
{% endblock %}